/* ============================================================
 * keys.h — the bindings a person chose, over the ones we compiled
 *
 * RFC 0001 promised this in its own words: "novi-shell's bindings live
 * in a plaintext config file a user can edit directly, the same
 * config-first philosophy as everything else in this repo, not a
 * GUI-only settings dialog with nothing backing it on disk." They did
 * not. Every shortcut in this desktop was a compiled-in constant, so
 * the one part of a desktop people reliably want to change was the one
 * part they could not.
 *
 * /etc/novi/keys.conf is `<action> = <binding>`, one per line, where
 * <action> is a row's `name` in keybindings.h and <binding> is a
 * `Super+Shift+Q`-shaped string (or `off`). Anything the file does not
 * mention keeps the compiled default, which is the same additive rule
 * `system.conf` follows for packages and users: a document that has to
 * list everything in order to change one thing is a document nobody
 * edits twice.
 *
 * BOTH BINARIES LOAD IT. novi-shell dispatches from the result and
 * `novi-launcher --keys` displays the result, exactly as they already
 * shared the compiled table -- and that is the whole reason this is a
 * loader in common/ rather than a parser inside the compositor. A
 * sheet that lists the defaults while the compositor honours an
 * override is a document that confidently tells you the wrong key,
 * which keybindings.h opens by saying is worse than no sheet at all.
 * ============================================================ */
#ifndef NOVI_KEYS_H
#define NOVI_KEYS_H

#include <stdbool.h>
#include <stddef.h>

#include "keybindings.h"

#define NOVI_KEYS_PATH "/etc/novi/keys.conf"

/* Long enough for "Super + Shift + XF86AudioRaiseVolume". A binding
 * that does not fit is truncated rather than dropped: the sheet is
 * showing a key somebody chose, and half of its name beats none of
 * it. */
#define NOVI_KEYS_TEXT_MAX 64

struct novi_keys {
	struct novi_binding v[NOVI_BINDINGS_COUNT];
	/* How each row READS -- "Super + Return" -- generated by
	 * novi_keys_format() for every row, default or overridden. There
	 * is no hand-written spelling anywhere: a sheet whose text is a
	 * second copy of the binding is a sheet that can disagree with
	 * what fires, and keybindings.h opens by saying that is worse
	 * than having no sheet. */
	char text[NOVI_BINDINGS_COUNT][NOVI_KEYS_TEXT_MAX];

	/* What the file did, for whoever has to find out why their key
	 * does nothing. A count on its own is enough for the sheet's
	 * footer; the log lines name the lines. */
	int overridden;  /* rows a line actually moved */
	int unreadable;  /* lines this build could not make sense of */
	int conflicts;   /* rows disabled for landing on a taken binding */
};

/* Does this kernel command line say to ignore the file? `novi.keys=off`
 * is the way back for somebody who has locked themselves out of their
 * own desktop with it -- the same escape hatch `novi.state=off` is for
 * boot convergence, and for the same reason: a machine that reads a
 * file at startup can be made unusable by that file, and the fix has
 * to be reachable from the bootloader.
 *
 * Takes the text rather than reading /proc/cmdline so it can be
 * tested; novi_keys_load() does the reading.
 *
 * Matched as a whole word: `xnovi.keys=off` and `novi.keys=office` are
 * not this. */
bool novi_keys_cmdline_off(const char *cmdline);

/* The compiled defaults, ready to dispatch from. Always succeeds --
 * a client that never loads a file draws and dispatches exactly what
 * it always did. */
void novi_keys_defaults(struct novi_keys *k);

/* Applies `path` over `k`. Returns the number of lines it could not
 * use (also left in `k->unreadable`); a missing file is not one of
 * them and returns 0. Never leaves `k` half-applied in a way that
 * loses a row: a line that cannot be parsed leaves that row alone. */
int novi_keys_load(struct novi_keys *k, const char *path);

/* Where novi_keys_load() looks for the escape hatch. */
#define NOVI_KEYS_CMDLINE "/proc/cmdline"

/* "Super+Shift+q" -> mods and keysym. False for anything it cannot
 * make sense of. `off`, `none` and `disabled` parse as success with
 * *sym == XKB_KEY_NoSymbol, which is how a row is switched off. */
bool novi_keys_parse(const char *spec, unsigned *mods, xkb_keysym_t *sym);

/* The inverse, for display: "Super + Shift + Q". DIGIT_RANGE rows
 * render as "… + 1…9" because that is what they match. */
void novi_keys_format(unsigned mods, xkb_keysym_t sym, unsigned flags,
	char *out, size_t cap);

/* ── Writing one back ─────────────────────────────────────────────────
 *
 * RFC 0037 roadmap 1. The file is hand-edited prose with comments, so
 * the model is `novi-state`'s `state_set` — a SURGICAL edit that
 * preserves every other byte — and emphatically not a rewrite from the
 * parsed table. A settings panel that rewrites this file turns it into
 * a machine-owned blob the first time somebody uses the panel, and the
 * whole claim RFC 0037 makes is that the GUI and a text editor write
 * the same document.
 *
 * `spec` is a binding string (`Super+Shift+T`, `off`), or NULL to
 * REMOVE the line and go back to the compiled default. Removing is a
 * delete rather than a comment-out: a commented line is documentation,
 * and inventing documentation on somebody's behalf is not this
 * function's job.
 *
 * Refuses an action this build does not have and a spec
 * novi_keys_parse() cannot read, for the reason the loader refuses an
 * unknown modifier word rather than skipping it: writing a line that
 * does something other than what it says is worse than writing
 * nothing.
 *
 * A COMMENTED LINE IS NOT A MATCH. The shipped keys.conf is 87 lines
 * and every one of them is a comment — it is the documentation as well
 * as the file — so a matcher that ignored the `#` would find
 * `# session.lock = Super+L` in the middle of a prose block and
 * uncomment it. That is the trap CLAUDE.md records about editing
 * `system.conf` by hand ("read a diff for what it UNCOMMENTS"), from
 * the writing side. An action with no live line is APPENDED.
 *
 * Returns 0, or an errno: EINVAL for a bad action or spec, and
 * whatever open/write/rename gave otherwise (EACCES is the ordinary
 * one — this file is root-owned).
 */
int novi_keys_write(const char *path, const char *action, const char *spec);

/* Is there a live (uncommented) line for this action? The panel needs
 * it to say "default" versus "yours" without re-deriving it from a
 * comparison against the compiled table — two rows can hold the same
 * binding for different reasons, and "you set this to what it already
 * was" is a true and useful thing to show. */
bool novi_keys_is_set(const char *path, const char *action);

#endif
