/* ============================================================
 * keys.h — the bindings a person chose, over the ones we compiled
 *
 * RFC 0001 promised this in its own words: "novi-shell's bindings live
 * in a plaintext config file a user can edit directly, the same
 * config-first philosophy as everything else in this repo, not a
 * GUI-only settings dialog with nothing backing it on disk." They did
 * not. Every shortcut in this desktop was a compiled-in constant, so
 * the one part of a desktop people reliably want to change was the one
 * part they could not.
 *
 * /etc/novi/keys.conf is `<action> = <binding>`, one per line, where
 * <action> is a row's `name` in keybindings.h and <binding> is a
 * `Super+Shift+Q`-shaped string (or `off`). Anything the file does not
 * mention keeps the compiled default, which is the same additive rule
 * `system.conf` follows for packages and users: a document that has to
 * list everything in order to change one thing is a document nobody
 * edits twice.
 *
 * BOTH BINARIES LOAD IT. novi-shell dispatches from the result and
 * `novi-launcher --keys` displays the result, exactly as they already
 * shared the compiled table -- and that is the whole reason this is a
 * loader in common/ rather than a parser inside the compositor. A
 * sheet that lists the defaults while the compositor honours an
 * override is a document that confidently tells you the wrong key,
 * which keybindings.h opens by saying is worse than no sheet at all.
 * ============================================================ */
#ifndef NOVI_KEYS_H
#define NOVI_KEYS_H

#include <stdbool.h>
#include <stddef.h>

#include "keybindings.h"

#define NOVI_KEYS_PATH "/etc/novi/keys.conf"

/* Long enough for "Super + Shift + XF86AudioRaiseVolume". A binding
 * that does not fit is truncated rather than dropped: the sheet is
 * showing a key somebody chose, and half of its name beats none of
 * it. */
#define NOVI_KEYS_TEXT_MAX 64

struct novi_keys {
	struct novi_binding v[NOVI_BINDINGS_COUNT];
	/* How each row READS -- "Super + Return" -- generated by
	 * novi_keys_format() for every row, default or overridden. There
	 * is no hand-written spelling anywhere: a sheet whose text is a
	 * second copy of the binding is a sheet that can disagree with
	 * what fires, and keybindings.h opens by saying that is worse
	 * than having no sheet. */
	char text[NOVI_BINDINGS_COUNT][NOVI_KEYS_TEXT_MAX];

	/* What the file did, for whoever has to find out why their key
	 * does nothing. A count on its own is enough for the sheet's
	 * footer; the log lines name the lines. */
	int overridden;  /* rows a line actually moved */
	int unreadable;  /* lines this build could not make sense of */
	int conflicts;   /* rows disabled for landing on a taken binding */
};

/* Does this kernel command line say to ignore the file? `novi.keys=off`
 * is the way back for somebody who has locked themselves out of their
 * own desktop with it -- the same escape hatch `novi.state=off` is for
 * boot convergence, and for the same reason: a machine that reads a
 * file at startup can be made unusable by that file, and the fix has
 * to be reachable from the bootloader.
 *
 * Takes the text rather than reading /proc/cmdline so it can be
 * tested; novi_keys_load() does the reading.
 *
 * Matched as a whole word: `xnovi.keys=off` and `novi.keys=office` are
 * not this. */
bool novi_keys_cmdline_off(const char *cmdline);

/* The compiled defaults, ready to dispatch from. Always succeeds --
 * a client that never loads a file draws and dispatches exactly what
 * it always did. */
void novi_keys_defaults(struct novi_keys *k);

/* Applies `path` over `k`. Returns the number of lines it could not
 * use (also left in `k->unreadable`); a missing file is not one of
 * them and returns 0. Never leaves `k` half-applied in a way that
 * loses a row: a line that cannot be parsed leaves that row alone. */
int novi_keys_load(struct novi_keys *k, const char *path);

/* Where novi_keys_load() looks for the escape hatch. */
#define NOVI_KEYS_CMDLINE "/proc/cmdline"

/* "Super+Shift+q" -> mods and keysym. False for anything it cannot
 * make sense of. `off`, `none` and `disabled` parse as success with
 * *sym == XKB_KEY_NoSymbol, which is how a row is switched off. */
bool novi_keys_parse(const char *spec, unsigned *mods, xkb_keysym_t *sym);

/* The inverse, for display: "Super + Shift + Q". DIGIT_RANGE rows
 * render as "… + 1…9" because that is what they match. */
void novi_keys_format(unsigned mods, xkb_keysym_t sym, unsigned flags,
	char *out, size_t cap);

#endif
