#!/usr/bin/env bash
# mkiso.sh — Build a bootable hybrid ISO for Novi Linux
# Usage: sudo ./mkiso.sh [--rootfs <dir>] [--output <file>]
# Requires: mksquashfs, grub-mkrescue, grub-mkimage, xorriso, cpio, gzip

set -euo pipefail

# ─── Defaults ────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
# shellcheck source=../build/00-versions.sh
source "${REPO_ROOT}/build/00-versions.sh"

# ROOTFS_DIR/KERNEL_IMAGE default to where build/*.sh actually produce them
# (${ROOTFS}, i.e. /build/rootfs, from the sourced 00-versions.sh -- that
# file's own BUILD_DIR is hardcoded to /build, unrelated to REPO_ROOT).
# ISO_WORK_DIR is this script's own, unrelated concept: where mkiso.sh
# stages the ISO it's building. Deliberately NOT named BUILD_DIR -- that
# name is already taken by the sourced 00-versions.sh's export, and a
# same-named local default here would silently pick up its value instead
# of falling back to the repo-relative path intended below.
ROOTFS_DIR="${ROOTFS_DIR:-${ROOTFS}}"
ISO_WORK_DIR="${ISO_WORK_DIR:-${REPO_ROOT}/build}"
ISO_DIR="${ISO_WORK_DIR}/isoroot"
# Not "${1:-...}": this script takes --flag value pairs, not a bare
# positional arg, so grabbing raw $1 here would take the *next flag
# name* (e.g. "--rootfs") as the output path whenever --output isn't
# the first argument passed.
OUTPUT_ISO="${OUTPUT_ISO:-${ISO_WORK_DIR}/novi.iso}"
SQUASHFS_COMP="${SQUASHFS_COMP:-zstd}"     # xz | zstd | lz4
KERNEL_IMAGE="${KERNEL_IMAGE:-${ROOTFS}/boot/vmlinuz-${LINUX_VERSION}}"
INITRAMFS_IMAGE="${INITRAMFS_IMAGE:-${ISO_WORK_DIR}/initramfs.cpio.gz}"
GRUB_TIMEOUT="${GRUB_TIMEOUT:-5}"
ISO_LABEL="NOVI"
ISO_VERSION="0.1.0"

# ─── Argument parsing ─────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --rootfs)  ROOTFS_DIR="$2"; shift 2 ;;
        --output)  OUTPUT_ISO="$2"; shift 2 ;;
        --kernel)  KERNEL_IMAGE="$2"; shift 2 ;;
        --initrd)  INITRAMFS_IMAGE="$2"; shift 2 ;;
        --comp)    SQUASHFS_COMP="$2"; shift 2 ;;
        -h|--help)
            echo "Usage: $0 [--rootfs DIR] [--output FILE] [--kernel FILE] [--initrd FILE] [--comp ALGO]"
            exit 0
            ;;
        *)  echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

# ─── Prerequisite checks ──────────────────────────────────────────────────────
require() {
    local cmd="$1"
    if ! command -v "${cmd}" &>/dev/null; then
        echo "ERROR: Required tool '${cmd}' not found in PATH." >&2
        exit 1
    fi
}
require mksquashfs
require grub-mkrescue
require xorriso
require find
require cpio
require gzip

[[ -d "${ROOTFS_DIR}" ]] || { echo "ERROR: rootfs not found at ${ROOTFS_DIR}"; exit 1; }
[[ -f "${KERNEL_IMAGE}" ]] || { echo "ERROR: kernel image not found at ${KERNEL_IMAGE}"; exit 1; }

# ─── Build initramfs if not present ──────────────────────────────────────────
if [[ ! -f "${INITRAMFS_IMAGE}" ]]; then
    echo ">>> Initramfs not found, building with mkinitramfs.sh..."
    # Invoked via `bash`, not executed directly: scripts/*.sh are tracked
    # in git as mode 100644 (confirmed with `git ls-files -s`, true for
    # most of this repo's scripts, not just this one), so a fresh clone
    # has no execute bit on mkinitramfs.sh regardless of what's on any
    # one contributor's working copy -- direct execution fails outright
    # with "Permission denied" on a from-scratch checkout.
    bash "${SCRIPT_DIR}/mkinitramfs.sh" --output "${INITRAMFS_IMAGE}"
fi

# ─── Prepare ISO tree ─────────────────────────────────────────────────────────
echo ">>> Preparing ISO directory tree at ${ISO_DIR} ..."
rm -rf "${ISO_DIR}"
mkdir -p \
    "${ISO_DIR}/boot/grub" \
    "${ISO_DIR}/live" \
    "${ISO_DIR}/EFI/BOOT"

# ─── Squash the rootfs ────────────────────────────────────────────────────────
SQUASHFS_IMG="${ISO_DIR}/live/filesystem.squashfs"
echo ">>> Squashing rootfs (${SQUASHFS_COMP}) → ${SQUASHFS_IMG} ..."

# Exclude pseudo/runtime dirs from squash
MKSQUASHFS_EXCLUDES=(
    "${ROOTFS_DIR}/proc"
    "${ROOTFS_DIR}/sys"
    "${ROOTFS_DIR}/dev"
    "${ROOTFS_DIR}/run"
    "${ROOTFS_DIR}/tmp"
)

mksquashfs \
    "${ROOTFS_DIR}" \
    "${SQUASHFS_IMG}" \
    -comp "${SQUASHFS_COMP}" \
    -b 1M \
    -no-progress \
    -no-recovery \
    -noappend \
    -wildcards \
    -e proc sys dev run tmp \
    2>&1 | grep -v "^$"

echo ">>> squashfs size: $(du -sh "${SQUASHFS_IMG}" | cut -f1)"

# ─── Copy kernel and initramfs ────────────────────────────────────────────────
echo ">>> Copying kernel and initramfs ..."
cp "${KERNEL_IMAGE}"    "${ISO_DIR}/boot/vmlinuz"
cp "${INITRAMFS_IMAGE}" "${ISO_DIR}/boot/initramfs.cpio.gz"

# ─── Write GRUB config ────────────────────────────────────────────────────────
echo ">>> Writing GRUB configuration ..."
cat > "${ISO_DIR}/boot/grub/grub.cfg" <<GRUBCFG
# Novi Linux — GRUB configuration
# "Linux, reimagined."
# Generated by mkiso.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')

set default=0
set timeout=${GRUB_TIMEOUT}
set timeout_style=menu

# Serial console (in addition to the graphical/tty0 one) so the boot menu
# and kernel messages are visible when run headless -- a real distro use
# case (cloud VMs, QEMU -nographic), not just a debug convenience.
insmod serial
serial --unit=0 --speed=115200
terminal_input console serial
terminal_output console serial

# Appearance
if [ -f \$prefix/theme/theme.txt ]; then
    insmod gfxterm
    insmod vbe
    insmod png
    set gfxmode=auto
    terminal_output gfxterm
fi

insmod all_video
insmod gzio
insmod part_gpt
insmod part_msdos
insmod fat
insmod iso9660
insmod squash4

# ── Boot entries ──────────────────────────────────────────────────────────────

menuentry "Novi Linux ${ISO_VERSION} — Live" --class linux {
    echo "Loading Novi..."
    linux  /boot/vmlinuz \
           boot=live \
           root=live:/dev/disk/by-label/${ISO_LABEL} \
           live-media=/dev/disk/by-label/${ISO_LABEL} \
           live-media-label=${ISO_LABEL} \
           rd.live.image \
           rd.live.squashimg=live/filesystem.squashfs \
           quiet splash \
           rw \
           loglevel=3 \
           console=tty0 \
           console=ttyS0,115200n8 \
           mitigations=auto \
           iommu=pt \
           vt.global_cursor_default=0
    echo "Loading initramfs..."
    initrd /boot/initramfs.cpio.gz
}

menuentry "Novi Linux ${ISO_VERSION} — Live Desktop" --class linux {
    echo "Loading Novi (desktop)..."
    linux  /boot/vmlinuz \
           boot=live \
           root=live:/dev/disk/by-label/${ISO_LABEL} \
           live-media=/dev/disk/by-label/${ISO_LABEL} \
           live-media-label=${ISO_LABEL} \
           rd.live.image \
           rd.live.squashimg=live/filesystem.squashfs \
           novi.live.desktop \
           quiet splash \
           rw \
           loglevel=3 \
           console=tty0 \
           console=ttyS0,115200n8 \
           mitigations=auto \
           iommu=pt \
           vt.global_cursor_default=0
    echo "Loading initramfs..."
    initrd /boot/initramfs.cpio.gz
}

menuentry "Novi Linux ${ISO_VERSION} — Safe Mode" --class linux {
    echo "Loading Novi (safe mode)..."
    linux  /boot/vmlinuz \
           boot=live \
           root=live:/dev/disk/by-label/${ISO_LABEL} \
           live-media=/dev/disk/by-label/${ISO_LABEL} \
           live-media-label=${ISO_LABEL} \
           rd.live.image \
           rd.live.squashimg=live/filesystem.squashfs \
           nomodeset \
           nosplash \
           rw \
           loglevel=7 \
           console=tty0 \
           console=ttyS0,115200n8
    echo "Loading initramfs..."
    initrd /boot/initramfs.cpio.gz
}

menuentry "Memory Test (memtest86+)" --class memtest {
    if [ -f /boot/memtest86+ ]; then
        linux16 /boot/memtest86+
    else
        echo "memtest86+ not found."
        sleep 3
    fi
}

menuentry "Boot from local disk" --class hdd {
    exit 1
}
GRUBCFG

# ─── Optional: copy memtest86+ if available ───────────────────────────────────
MEMTEST_PATHS=(
    "/boot/memtest86+"
    "/usr/share/memtest86+/memtest.bin"
    "/usr/lib/memtest86+/memtest.bin"
)
for mt in "${MEMTEST_PATHS[@]}"; do
    if [[ -f "${mt}" ]]; then
        echo ">>> Found memtest86+, including in ISO ..."
        cp "${mt}" "${ISO_DIR}/boot/memtest86+"
        break
    fi
done

# ─── Stage BIOS boot artifacts for the on-disk installer ─────────────────────
#
# RFC 0003. `novi-install` has to make a target disk bootable, but the
# Novi rootfs contains no bootloader at all -- there is no grub-install
# to run on the installed system, and building GRUB into the rootfs
# just to install it once is a lot of weight for a one-shot job.
#
# Instead, split what grub-install does across build time and install
# time: the two pieces it writes to disk are generated HERE, on a build
# host that already has GRUB's tools (CONTRIBUTING.md lists
# grub-common/grub-pc-bin as prerequisites), shipped inside the ISO,
# and merely *placed* by the installer. The installer then needs no
# GRUB tooling at all -- only `dd` and `cp`, both of which BusyBox has.
#
#   boot.img  512 bytes -> the MBR's boot code (first 446 bytes of it)
#   core.img  ~30KB     -> the post-MBR gap; knows how to read ext2 and
#                          find /boot/grub on the root partition
#   i386-pc/  modules   -> what core.img loads once it can read the fs
#
# The prefix baked into core.img is where it looks for those modules
# and grub.cfg, so it has to match the layout novi-install creates
# (single ext2/4 partition, msdos table, /boot/grub on it).
# ─── Stage the package repository onto the media ─────────────────────────────
#
# The ISO carries the whole signed repository (RFC 0007). That is what
# makes the base image console-only without making the desktop
# network-only: /etc/novi/pkg.conf points at /run/live/novi-repo, so a
# live system can `pkg install novi-desktop` with no network, and
# `novi-install --profile desktop` can put one on a target machine that
# has never been online. Signature and hash verification are identical
# either way -- only the transport differs.
NOVI_REPO_DIR="${NOVI_REPO_DIR:-${BUILD_DIR}/repo}"
if [[ -f "${NOVI_REPO_DIR}/index" ]]; then
    echo ">>> Staging the package repository from ${NOVI_REPO_DIR} ..."
    mkdir -p "${ISO_DIR}/novi-repo"
    cp -a "${NOVI_REPO_DIR}"/. "${ISO_DIR}/novi-repo/"
    # The private signing key lives in ${BUILD_DIR}/keys and never in
    # the repo directory, but check anyway: shipping one on an ISO is
    # the kind of mistake that cannot be taken back once published.
    find "${ISO_DIR}/novi-repo" -name '*.key' -o -name '*.pem' | while read -r k; do
        echo "REFUSING: private key material found in the repository: ${k}" >&2
        exit 1
    done
    echo ">>> repository: $(ls "${ISO_DIR}/novi-repo"/*.pkg.tar.gz 2>/dev/null | wc -l) package(s), $(du -sh "${ISO_DIR}/novi-repo" | cut -f1)"
else
    echo ">>> WARNING: no package repository at ${NOVI_REPO_DIR} -- the ISO will" >&2
    echo ">>>          have no desktop to install. Run build/20-repo.sh first." >&2
fi

echo ">>> Staging BIOS boot artifacts for the installer ..."
GRUB_LIB_DIR="/usr/lib/grub/i386-pc"
if [[ -d "${GRUB_LIB_DIR}" ]] && command -v grub-mkimage &>/dev/null; then
    NOVI_BOOT_DIR="${ISO_DIR}/novi-boot"
    mkdir -p "${NOVI_BOOT_DIR}"
    cp "${GRUB_LIB_DIR}/boot.img" "${NOVI_BOOT_DIR}/boot.img"
    # The module list is the minimum needed to get from the gap to a
    # kernel: read an msdos partition table, read the ext2/4 filesystem
    # on it, then run a normal menu and boot Linux.
    grub-mkimage \
        -O i386-pc \
        -o "${NOVI_BOOT_DIR}/core.img" \
        -p '(hd0,msdos1)/boot/grub' \
        biosdisk part_msdos ext2 normal linux configfile search \
        search_fs_uuid search_label echo test ls boot
    mkdir -p "${NOVI_BOOT_DIR}/i386-pc"
    cp "${GRUB_LIB_DIR}"/*.mod "${GRUB_LIB_DIR}"/*.lst "${NOVI_BOOT_DIR}/i386-pc/" 2>/dev/null || true
    echo ">>> BIOS boot artifacts: boot.img $(stat -c%s "${NOVI_BOOT_DIR}/boot.img")B, core.img $(stat -c%s "${NOVI_BOOT_DIR}/core.img")B, $(ls "${NOVI_BOOT_DIR}/i386-pc" | wc -l) modules"
else
    # Not fatal: the ISO still boots and runs live. Only `novi-install`
    # is affected, and it checks for these and says so plainly rather
    # than producing an unbootable disk.
    echo ">>> WARNING: GRUB tools/modules not found -- ISO will boot live," >&2
    echo ">>>          but novi-install will refuse to install from it." >&2
fi

# ─── Write filesystem manifest ────────────────────────────────────────────────
echo ">>> Writing filesystem manifest ..."
if command -v chroot &>/dev/null && [[ -f "${ROOTFS_DIR}/usr/bin/dpkg" ]]; then
    chroot "${ROOTFS_DIR}" dpkg-query -W --showformat='${Package} ${Version}\n' \
        > "${ISO_DIR}/live/filesystem.manifest" 2>/dev/null || true
fi

# Record squashfs size for installer
du -sx --block-size=1 "${ROOTFS_DIR}" 2>/dev/null \
    | cut -f1 > "${ISO_DIR}/live/filesystem.size" || true

# ─── Build ISO with grub-mkrescue ────────────────────────────────────────────
echo ">>> Building hybrid ISO with grub-mkrescue ..."
mkdir -p "$(dirname "${OUTPUT_ISO}")"

# Source directory as a plain trailing positional arg -- the standard
# grub-mkrescue invocation. The previous "-- SRCDIR graft=point" form
# isn't valid input for this xorriso version's -as mkisofs emulation
# ("Not a known command: '...'") and the graft-point override was
# redundant anyway: boot/grub/grub.cfg is already written inside
# ISO_DIR at that exact path above.
grub-mkrescue \
    --output="${OUTPUT_ISO}" \
    --verbose \
    -volid "${ISO_LABEL}" \
    "${ISO_DIR}" \
    2>&1

# ─── Make hybrid (MBR + GPT + EFI) ──────────────────────────────────────────
# grub-mkrescue already produces a hybrid image; verify with isohybrid info
if command -v xorriso &>/dev/null; then
    echo ">>> ISO info (xorriso) ..."
    xorriso -indev "${OUTPUT_ISO}" -report_el_torito as_mkisofs 2>/dev/null | head -20 || true
fi

# ─── Print result ─────────────────────────────────────────────────────────────
ISO_SIZE="$(du -sh "${OUTPUT_ISO}" | cut -f1)"
echo ""
echo "╔════════════════════════════════════════════════════╗"
echo "║  Novi Linux ISO — Build Complete                   ║"
echo "╠════════════════════════════════════════════════════╣"
printf "║  Output : %-41s║\n" "${OUTPUT_ISO}"
printf "║  Size   : %-41s║\n" "${ISO_SIZE}"
printf "║  Label  : %-41s║\n" "${ISO_LABEL}"
printf "║  Comp   : %-41s║\n" "${SQUASHFS_COMP}"
echo "╚════════════════════════════════════════════════════╝"
echo ""
echo "To write to USB:"
echo "  sudo dd if=${OUTPUT_ISO} of=/dev/sdX bs=4M status=progress oflag=sync"
echo "  # OR: sudo cp ${OUTPUT_ISO} /dev/sdX   (for hybrid ISOs)"
