#!/usr/bin/env bash
# mkiso.sh — Build a bootable hybrid ISO for Novi Linux
# Usage: sudo ./mkiso.sh [--rootfs <dir>] [--output <file>]
# Requires: mksquashfs, grub-mkrescue, grub-mkimage, xorriso, cpio, gzip

set -euo pipefail

# ─── Defaults ────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
# shellcheck source=../build/00-versions.sh
source "${REPO_ROOT}/build/00-versions.sh"

# ROOTFS_DIR/KERNEL_IMAGE default to where build/*.sh actually produce them
# (${ROOTFS}, i.e. /build/rootfs -- BUILD_DIR in 00-versions.sh is hardcoded
# absolute, unrelated to REPO_ROOT). BUILD_DIR below is this script's own,
# unrelated concept: where mkiso.sh stages the ISO it's building.
ROOTFS_DIR="${ROOTFS_DIR:-${ROOTFS}}"
BUILD_DIR="${BUILD_DIR:-${REPO_ROOT}/build}"
ISO_DIR="${BUILD_DIR}/isoroot"
# Not "${1:-...}": this script takes --flag value pairs, not a bare
# positional arg, so grabbing raw $1 here would take the *next flag
# name* (e.g. "--rootfs") as the output path whenever --output isn't
# the first argument passed.
OUTPUT_ISO="${OUTPUT_ISO:-${BUILD_DIR}/novi.iso}"
SQUASHFS_COMP="${SQUASHFS_COMP:-zstd}"     # xz | zstd | lz4
KERNEL_IMAGE="${KERNEL_IMAGE:-${ROOTFS}/boot/vmlinuz-${LINUX_VERSION}}"
INITRAMFS_IMAGE="${INITRAMFS_IMAGE:-${BUILD_DIR}/initramfs.cpio.gz}"
GRUB_TIMEOUT="${GRUB_TIMEOUT:-5}"
ISO_LABEL="NOVI"
ISO_VERSION="0.1.0"

# ─── Argument parsing ─────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --rootfs)  ROOTFS_DIR="$2"; shift 2 ;;
        --output)  OUTPUT_ISO="$2"; shift 2 ;;
        --kernel)  KERNEL_IMAGE="$2"; shift 2 ;;
        --initrd)  INITRAMFS_IMAGE="$2"; shift 2 ;;
        --comp)    SQUASHFS_COMP="$2"; shift 2 ;;
        -h|--help)
            echo "Usage: $0 [--rootfs DIR] [--output FILE] [--kernel FILE] [--initrd FILE] [--comp ALGO]"
            exit 0
            ;;
        *)  echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

# ─── Prerequisite checks ──────────────────────────────────────────────────────
require() {
    local cmd="$1"
    if ! command -v "${cmd}" &>/dev/null; then
        echo "ERROR: Required tool '${cmd}' not found in PATH." >&2
        exit 1
    fi
}
require mksquashfs
require grub-mkrescue
require xorriso
require find
require cpio
require gzip

[[ -d "${ROOTFS_DIR}" ]] || { echo "ERROR: rootfs not found at ${ROOTFS_DIR}"; exit 1; }
[[ -f "${KERNEL_IMAGE}" ]] || { echo "ERROR: kernel image not found at ${KERNEL_IMAGE}"; exit 1; }

# ─── Build initramfs if not present ──────────────────────────────────────────
if [[ ! -f "${INITRAMFS_IMAGE}" ]]; then
    echo ">>> Initramfs not found, building with mkinitramfs.sh..."
    "${SCRIPT_DIR}/mkinitramfs.sh" --output "${INITRAMFS_IMAGE}"
fi

# ─── Prepare ISO tree ─────────────────────────────────────────────────────────
echo ">>> Preparing ISO directory tree at ${ISO_DIR} ..."
rm -rf "${ISO_DIR}"
mkdir -p \
    "${ISO_DIR}/boot/grub" \
    "${ISO_DIR}/live" \
    "${ISO_DIR}/EFI/BOOT"

# ─── Squash the rootfs ────────────────────────────────────────────────────────
SQUASHFS_IMG="${ISO_DIR}/live/filesystem.squashfs"
echo ">>> Squashing rootfs (${SQUASHFS_COMP}) → ${SQUASHFS_IMG} ..."

# Exclude pseudo/runtime dirs from squash
MKSQUASHFS_EXCLUDES=(
    "${ROOTFS_DIR}/proc"
    "${ROOTFS_DIR}/sys"
    "${ROOTFS_DIR}/dev"
    "${ROOTFS_DIR}/run"
    "${ROOTFS_DIR}/tmp"
)

mksquashfs \
    "${ROOTFS_DIR}" \
    "${SQUASHFS_IMG}" \
    -comp "${SQUASHFS_COMP}" \
    -b 1M \
    -no-progress \
    -no-recovery \
    -noappend \
    -wildcards \
    -e proc sys dev run tmp \
    2>&1 | grep -v "^$"

echo ">>> squashfs size: $(du -sh "${SQUASHFS_IMG}" | cut -f1)"

# ─── Copy kernel and initramfs ────────────────────────────────────────────────
echo ">>> Copying kernel and initramfs ..."
cp "${KERNEL_IMAGE}"    "${ISO_DIR}/boot/vmlinuz"
cp "${INITRAMFS_IMAGE}" "${ISO_DIR}/boot/initramfs.cpio.gz"

# ─── Write GRUB config ────────────────────────────────────────────────────────
echo ">>> Writing GRUB configuration ..."
cat > "${ISO_DIR}/boot/grub/grub.cfg" <<GRUBCFG
# Novi Linux — GRUB configuration
# "Linux, reimagined."
# Generated by mkiso.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')

set default=0
set timeout=${GRUB_TIMEOUT}
set timeout_style=menu

# Appearance
if [ -f \$prefix/theme/theme.txt ]; then
    insmod gfxterm
    insmod vbe
    insmod png
    set gfxmode=auto
    terminal_output gfxterm
fi

insmod all_video
insmod gzio
insmod part_gpt
insmod part_msdos
insmod fat
insmod iso9660
insmod squash4

# ── Boot entries ──────────────────────────────────────────────────────────────

menuentry "Novi Linux ${ISO_VERSION} — Live" --class linux {
    echo "Loading Novi..."
    linux  /boot/vmlinuz \
           boot=live \
           root=live:/dev/disk/by-label/${ISO_LABEL} \
           live-media=/dev/disk/by-label/${ISO_LABEL} \
           live-media-label=${ISO_LABEL} \
           rd.live.image \
           rd.live.squashimg=live/filesystem.squashfs \
           quiet splash \
           rw \
           loglevel=3 \
           mitigations=auto \
           iommu=pt \
           vt.global_cursor_default=0
    echo "Loading initramfs..."
    initrd /boot/initramfs.cpio.gz
}

menuentry "Novi Linux ${ISO_VERSION} — Safe Mode" --class linux {
    echo "Loading Novi (safe mode)..."
    linux  /boot/vmlinuz \
           boot=live \
           root=live:/dev/disk/by-label/${ISO_LABEL} \
           live-media=/dev/disk/by-label/${ISO_LABEL} \
           live-media-label=${ISO_LABEL} \
           rd.live.image \
           rd.live.squashimg=live/filesystem.squashfs \
           nomodeset \
           nosplash \
           rw \
           loglevel=7
    echo "Loading initramfs..."
    initrd /boot/initramfs.cpio.gz
}

menuentry "Memory Test (memtest86+)" --class memtest {
    if [ -f /boot/memtest86+ ]; then
        linux16 /boot/memtest86+
    else
        echo "memtest86+ not found."
        sleep 3
    fi
}

menuentry "Boot from local disk" --class hdd {
    exit 1
}
GRUBCFG

# ─── Optional: copy memtest86+ if available ───────────────────────────────────
MEMTEST_PATHS=(
    "/boot/memtest86+"
    "/usr/share/memtest86+/memtest.bin"
    "/usr/lib/memtest86+/memtest.bin"
)
for mt in "${MEMTEST_PATHS[@]}"; do
    if [[ -f "${mt}" ]]; then
        echo ">>> Found memtest86+, including in ISO ..."
        cp "${mt}" "${ISO_DIR}/boot/memtest86+"
        break
    fi
done

# ─── Write filesystem manifest ────────────────────────────────────────────────
echo ">>> Writing filesystem manifest ..."
if command -v chroot &>/dev/null && [[ -f "${ROOTFS_DIR}/usr/bin/dpkg" ]]; then
    chroot "${ROOTFS_DIR}" dpkg-query -W --showformat='${Package} ${Version}\n' \
        > "${ISO_DIR}/live/filesystem.manifest" 2>/dev/null || true
fi

# Record squashfs size for installer
du -sx --block-size=1 "${ROOTFS_DIR}" 2>/dev/null \
    | cut -f1 > "${ISO_DIR}/live/filesystem.size" || true

# ─── Build ISO with grub-mkrescue ────────────────────────────────────────────
echo ">>> Building hybrid ISO with grub-mkrescue ..."
mkdir -p "$(dirname "${OUTPUT_ISO}")"

grub-mkrescue \
    --output="${OUTPUT_ISO}" \
    --verbose \
    -volid "${ISO_LABEL}" \
    -- \
    "${ISO_DIR}" \
    boot/grub/grub.cfg="${ISO_DIR}/boot/grub/grub.cfg" \
    2>&1

# ─── Make hybrid (MBR + GPT + EFI) ──────────────────────────────────────────
# grub-mkrescue already produces a hybrid image; verify with isohybrid info
if command -v xorriso &>/dev/null; then
    echo ">>> ISO info (xorriso) ..."
    xorriso -indev "${OUTPUT_ISO}" -report_el_torito as_mkisofs 2>/dev/null | head -20 || true
fi

# ─── Print result ─────────────────────────────────────────────────────────────
ISO_SIZE="$(du -sh "${OUTPUT_ISO}" | cut -f1)"
echo ""
echo "╔════════════════════════════════════════════════════╗"
echo "║  Novi Linux ISO — Build Complete                   ║"
echo "╠════════════════════════════════════════════════════╣"
printf "║  Output : %-41s║\n" "${OUTPUT_ISO}"
printf "║  Size   : %-41s║\n" "${ISO_SIZE}"
printf "║  Label  : %-41s║\n" "${ISO_LABEL}"
printf "║  Comp   : %-41s║\n" "${SQUASHFS_COMP}"
echo "╚════════════════════════════════════════════════════╝"
echo ""
echo "To write to USB:"
echo "  sudo dd if=${OUTPUT_ISO} of=/dev/sdX bs=4M status=progress oflag=sync"
echo "  # OR: sudo cp ${OUTPUT_ISO} /dev/sdX   (for hybrid ISOs)"
