# shellcheck shell=sh
# ============================================================
# lib-resolv.sh — the ONE writer of /run/novi/resolv.conf
#
# Installed at /usr/lib/novi/resolv.sh and sourced by both things that
# have a resolver to write: the udhcpc lease script (a lease offers
# servers) and the network service's static path (a lease never
# happens). RFC 0033.
#
# One file, one writer, for the same reason /usr/lib/novi/json.sh is
# the one escaper: the rule about which servers win -- a declared
# `network.dns` beats whatever the lease offered, `auto` is how you ask
# for the lease's answer -- is a policy, and a policy implemented twice
# is a policy that disagrees with itself. The first draft of the static
# path had its own copy and had already dropped the `search` line.
#
# THE RESOLVER IS RUNTIME STATE, NOT CONFIGURATION. It lands in /run
# and /etc/resolv.conf is a symlink to it, so a lease renewal cannot
# rewrite a file somebody committed to git. That predates this file and
# is the reason it lives where it does.
#
# Sourced, not executed: `.` is a SPECIAL BUILTIN, so sourcing a file
# that is not there ends the calling script immediately with status 2
# and nothing on stderr anyone would connect to a missing library.
# Every caller guards with [ -f ... ] (RFC 0029 learned that one).
# ============================================================

NOVI_RESOLV_RUN_DIR=/run/novi
NOVI_RESOLV_FILE="${NOVI_RESOLV_RUN_DIR}/resolv.conf"
NOVI_RESOLV_DNS_FILE="${NOVI_RESOLV_RUN_DIR}/network.dns"

# novi_write_resolv <source-label> <lease-servers> [search-domain]
#
#   source-label    what produced this, for the file's own header
#   lease-servers   space separated, from a DHCP lease; empty for static
#   search-domain   from the lease; optional
#
# Returns 1 -- and writes the file anyway -- when the result would name
# no server at all. That is a real outcome on a static machine whose
# `network.dns` was left at `auto`: there is no lease to learn from, so
# the honest answer is a resolver file with no nameserver in it and a
# caller that says so out loud. Writing nothing instead would leave a
# STALE resolv.conf from a previous configuration looking current.
novi_write_resolv() {
    local label="$1" lease="$2" search="${3:-}"
    local declared="" servers="" s

    [ -f "$NOVI_RESOLV_DNS_FILE" ] && declared="$(cat "$NOVI_RESOLV_DNS_FILE")"

    # A declared network.dns wins over whatever the lease offered: the
    # document is the source of truth, and `auto` is how you say you
    # want the lease's answer instead.
    case "$declared" in
        ""|auto) servers="$lease" ;;
        *)       servers="$(printf '%s' "$declared" | tr ',' ' ')" ;;
    esac

    mkdir -p "$NOVI_RESOLV_RUN_DIR"
    {
        printf '# Generated by %s. Runtime state, not configuration.\n' "$label"
        printf '# Declare a fixed resolver with: novi-state set network.dns 1.1.1.1,9.9.9.9\n'
        [ -n "$search" ] && printf 'search %s\n' "$search"
        for s in $servers; do
            printf 'nameserver %s\n' "$s"
        done
    } > "${NOVI_RESOLV_FILE}.new"
    # Temp file and rename: a resolver read while it is half-written is
    # a lookup failure nobody can reproduce.
    mv "${NOVI_RESOLV_FILE}.new" "$NOVI_RESOLV_FILE"

    [ -n "$servers" ]
}
